import { FeedbackItem, KpiMetric, SentimentDistribution, ThemeMetric, TimeSeriesPoint } from "@/types";

export const initialKpis: KpiMetric[] = [
  {
    title: "Total Feedback",
    value: "2,486",
    change: "+12.4%",
    changeType: "positive",
    subtitle: "vs last month",
  },
  {
    title: "Positive Sentiment",
    value: "58%",
    change: "+4.2%",
    changeType: "positive",
    subtitle: "1,442 responses",
  },
  {
    title: "Neutral Sentiment",
    value: "24%",
    change: "-1.5%",
    changeType: "neutral",
    subtitle: "596 responses",
  },
  {
    title: "Negative Sentiment",
    value: "18%",
    change: "-2.7%",
    changeType: "positive", // lower negative is positive
    subtitle: "448 responses",
  },
  {
    title: "Customer Satisfaction (CSAT)",
    value: "4.3 / 5.0",
    change: "+0.3",
    changeType: "positive",
    subtitle: "Based on 1,820 ratings",
  },
  {
    title: "Open Action Items",
    value: "87",
    change: "-14",
    changeType: "positive", // reduced issues is good
    subtitle: "12 high priority",
  },
];

export const sentimentDistribution: SentimentDistribution[] = [
  { name: "Positive", value: 1442, percentage: 58, color: "#10b981" },
  { name: "Neutral", value: 596, percentage: 24, color: "#f59e0b" },
  { name: "Negative", value: 448, percentage: 18, color: "#ef4444" },
];

export const themeMetrics: ThemeMetric[] = [
  { theme: "Performance & Load Times", count: 482, sentimentScore: 0.78, trend: "+15%", category: "Performance" },
  { theme: "Customer Support Speed", count: 394, sentimentScore: 0.92, trend: "+22%", category: "Support" },
  { theme: "Pricing & Tier Flexibility", count: 310, sentimentScore: 0.45, trend: "-4%", category: "Pricing" },
  { theme: "UI / Mobile Responsiveness", count: 288, sentimentScore: 0.81, trend: "+8%", category: "UX" },
  { theme: "Feature Request: Slack Sync", count: 245, sentimentScore: 0.88, trend: "+12%", category: "Feature Requests" },
  { theme: "Export Data Formatting", count: 184, sentimentScore: 0.52, trend: "+5%", category: "UX" },
];

export const timeSeriesData: TimeSeriesPoint[] = [
  { date: "Sep 01", total: 68, positive: 42, neutral: 16, negative: 10 },
  { date: "Sep 03", total: 84, positive: 50, neutral: 20, negative: 14 },
  { date: "Sep 05", total: 72, positive: 44, neutral: 18, negative: 10 },
  { date: "Sep 07", total: 95, positive: 60, neutral: 22, negative: 13 },
  { date: "Sep 09", total: 110, positive: 70, neutral: 25, negative: 15 },
  { date: "Sep 11", total: 105, positive: 68, neutral: 24, negative: 13 },
  { date: "Sep 13", total: 128, positive: 82, neutral: 28, negative: 18 },
  { date: "Sep 15", total: 140, positive: 90, neutral: 32, negative: 18 },
];

export const mockFeedbackList: FeedbackItem[] = [
  {
    id: "fb-101",
    customerName: "Sarah Jenkins",
    customerEmail: "sarah.j@techcorp.io",
    customerCompany: "TechCorp Global",
    title: "AI Analysis saved our product team 20 hours a week",
    content: "The automatic theme detection accurately flagged that users were struggling with our new onboarding flow. We fixed it within 2 days and conversion rose 14%.",
    rating: 5,
    sentiment: "positive",
    sentimentScore: 0.96,
    category: "ux",
    theme: "UI / Mobile Responsiveness",
    source: "G2",
    status: "resolved",
    createdAt: "2026-09-15T14:32:00Z",
  },
  {
    id: "fb-102",
    customerName: "David Miller",
    customerEmail: "d.miller@fintechcloud.com",
    customerCompany: "FinTech Cloud",
    title: "Dashboard loading is noticeably faster after latest update",
    content: "Reports used to take 5-10 seconds to generate. Now they appear almost instantly. Great work on query optimization!",
    rating: 5,
    sentiment: "positive",
    sentimentScore: 0.91,
    category: "performance",
    theme: "Performance & Load Times",
    source: "Intercom",
    status: "resolved",
    createdAt: "2026-09-15T11:15:00Z",
  },
  {
    id: "fb-103",
    customerName: "Elena Rostova",
    customerEmail: "elena@designhub.co",
    customerCompany: "DesignHub",
    title: "Need custom CSV export options for monthly executive reports",
    content: "The default PDF export is clean, but our BI team needs raw JSON or customized CSV column exports to merge with Salesforce data.",
    rating: 3,
    sentiment: "neutral",
    sentimentScore: 0.54,
    category: "feature_request",
    theme: "Export Data Formatting",
    source: "Email",
    status: "in_progress",
    createdAt: "2026-09-14T18:45:00Z",
  },
  {
    id: "fb-104",
    customerName: "Marcus Vance",
    customerEmail: "marcus@scaleups.net",
    customerCompany: "ScaleUp Systems",
    title: "Enterprise tier pricing is too steep for mid-market teams",
    content: "We love the Voice-of-Customer reports, but jumping from $299/mo to $1,499/mo just for SAML SSO feels aggressive for a 40-person company.",
    rating: 2,
    sentiment: "negative",
    sentimentScore: 0.28,
    category: "pricing",
    theme: "Pricing & Tier Flexibility",
    source: "Trustpilot",
    status: "new",
    createdAt: "2026-09-14T10:20:00Z",
  },
  {
    id: "fb-105",
    customerName: "Chloe Dupont",
    customerEmail: "chloe@saasmetrics.app",
    customerCompany: "SaaS Metrics",
    title: "Support team responded in under 3 minutes with full fix",
    content: "Had a webhook syncing error with Zendesk. Alex from support personally verified our payload and solved it on the first reply.",
    rating: 5,
    sentiment: "positive",
    sentimentScore: 0.98,
    category: "support",
    theme: "Customer Support Speed",
    source: "Zendesk",
    status: "resolved",
    createdAt: "2026-09-13T16:05:00Z",
  },
  {
    id: "fb-106",
    customerName: "Liam O'Connor",
    customerEmail: "liam@cloudops.dev",
    customerCompany: "CloudOps Dev",
    title: "Mobile drawer menu glitching on Safari iOS",
    content: "When clicking the sidebar toggle on iPhone 15 Pro, the backdrop flickers twice before locking. Harmless but distracting.",
    rating: 3,
    sentiment: "negative",
    sentimentScore: 0.35,
    category: "bug",
    theme: "UI / Mobile Responsiveness",
    source: "App Store",
    status: "in_progress",
    createdAt: "2026-09-12T09:14:00Z",
  },
  {
    id: "fb-107",
    customerName: "Aria Chen",
    customerEmail: "aria.c@nextgen.ai",
    customerCompany: "NextGen AI",
    title: "LOOP AI prompt responses are remarkably accurate",
    content: "I asked 'What are users saying about our billing page?' and LOOP AI extracted 12 specific quotes grouped by theme in 4 seconds.",
    rating: 5,
    sentiment: "positive",
    sentimentScore: 0.95,
    category: "ux",
    theme: "Feature Request: Slack Sync",
    source: "Intercom",
    status: "reviewed",
    createdAt: "2026-09-11T15:50:00Z",
  }
];
