import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { VoiceOfCustomerReportData } from "./index";

/**
 * Client-side Vector PDF Generator for Voice-of-Customer Reports
 */
export function downloadReportPDF(report: VoiceOfCustomerReportData) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const primaryColor = [37, 81, 245]; // Brand Blue
  const darkTextColor = [15, 23, 42];
  const mutedTextColor = [100, 116, 139];

  // Header Bar Branding
  doc.setFillColor(37, 81, 245);
  doc.rect(0, 0, 210, 18, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("LOOP Intelligence Platform", 14, 12);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Voice-of-Customer Executive Report", 140, 12);

  // Document Title & Metadata
  let y = 28;
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(report.title, 14, y);

  y += 7;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
  doc.text(`Organization: ${report.organizationName}  |  Period: ${new Date(report.dateFrom).toLocaleDateString()} - ${new Date(report.dateTo).toLocaleDateString()}`, 14, y);

  y += 5;
  doc.text(`Generated By: ${report.createdBy}  |  Date: ${new Date(report.generatedAt).toLocaleDateString()}  |  AI Engine: ${report.aiModel}`, 14, y);

  // Horizontal Divider Line
  y += 5;
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, y, 196, y);

  // Section 1: Executive Summary
  y += 8;
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("1. Executive Summary", 14, y);

  y += 6;
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(darkTextColor[0], darkTextColor[1], darkTextColor[2]);

  const cleanSummary = report.executiveSummary
    .replace(/###\s*/g, "")
    .replace(/\*\*/g, "");
  const summaryLines = doc.splitTextToSize(cleanSummary, 182);
  doc.text(summaryLines, 14, y);

  y += summaryLines.length * 4.5 + 6;

  // Section 2: Feedback Overview Table
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("2. Feedback Overview & Sentiment Breakdown", 14, y);

  y += 4;
  const metricsData = [
    [
      report.metrics.totalFeedback.toString(),
      `${report.metrics.positiveCount} (${report.metrics.positivePercent}%)`,
      `${report.metrics.neutralCount} (${report.metrics.neutralPercent}%)`,
      `${report.metrics.negativeCount} (${report.metrics.negativePercent}%)`,
      report.metrics.csatScore,
      report.metrics.openIssues.toString(),
    ],
  ];

  autoTable(doc, {
    startY: y,
    head: [["Total Feedback", "Positive", "Neutral", "Negative", "CSAT Rating", "Open Action Items"]],
    body: metricsData,
    theme: "grid",
    headStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: "bold", fontSize: 8 },
    bodyStyles: { fontSize: 9, fontStyle: "bold" },
    margin: { left: 14, right: 14 },
  });

  // @ts-ignore
  y = doc.lastAutoTable.finalY + 8;

  // Section 3: Top Customer Themes Table
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("3. Top Customer Themes", 14, y);

  y += 4;
  const themesRows = report.topThemes.map((t) => [
    t.theme,
    t.count.toString(),
    `${t.positiveCount} pos / ${t.negativeCount} neg`,
    `${t.sentimentScore} / 100`,
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Theme Name", "Volume", "Sentiment Breakdown", "Avg Sentiment Score"]],
    body: themesRows,
    theme: "striped",
    headStyles: { fillColor: [37, 81, 245], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 8 },
    bodyStyles: { fontSize: 8.5 },
    margin: { left: 14, right: 14 },
  });

  // @ts-ignore
  y = doc.lastAutoTable.finalY + 8;

  // Check Page Overflow
  if (y > 240) {
    doc.addPage();
    y = 20;
  }

  // Section 4: Anonymized Customer Voice
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("4. Representative Customer Excerpts", 14, y);

  y += 4;
  const voiceRows = report.customerVoice.map((v) => [
    v.label,
    v.sentiment,
    v.source,
    v.quote,
  ]);

  autoTable(doc, {
    startY: y,
    head: [["Customer Ref", "Sentiment", "Source", "Feedback Quote"]],
    body: voiceRows,
    theme: "grid",
    headStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42], fontStyle: "bold", fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    columnStyles: { 3: { cellWidth: 100 } },
    margin: { left: 14, right: 14 },
  });

  // Footer Watermark
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(mutedTextColor[0], mutedTextColor[1], mutedTextColor[2]);
    doc.text(`Confidential — Organization: ${report.organizationName}`, 14, 288);
    doc.text(`Page ${i} of ${pageCount}`, 180, 288);
  }

  // Save PDF file
  const filename = `LOOP_Voice_of_Customer_Report_${report.organizationName.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;
  doc.save(filename);
}
