"use client";

import * as React from "react";
import Link from "next/link";
import {
  FileSpreadsheet,
  Download,
  Sparkles,
  CheckCircle,
  Calendar,
  Eye,
  AlertCircle,
  RefreshCw,
} from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Modal } from "@/components/ui/modal";
import { formatDate } from "@/lib/utils";
import { downloadReportPDF } from "@/lib/reports/pdf-export";

export default function ReportsPage() {
  const [session, setSession] = React.useState<any>(null);
  const [reports, setReports] = React.useState<any[]>([]);
  const [loading, setLoading] = React.useState(true);

  // Generate Report Modal state
  const [modalOpen, setModalOpen] = React.useState(false);
  const [dateFrom, setDateFrom] = React.useState("2026-09-01");
  const [dateTo, setDateTo] = React.useState("2026-09-16");
  const [reportTitle, setReportTitle] = React.useState("");
  const [generating, setGenerating] = React.useState(false);
  const [error, setError] = React.useState("");
  const [toastMsg, setToastMsg] = React.useState("");

  const fetchReports = React.useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/reports");
      const data = await res.json();
      if (data.success) {
        setReports(data.data);
      }
    } catch (e) {
      console.error("Failed to load reports:", e);
    } finally {
      setLoading(false);
    }
  }, []);

  React.useEffect(() => {
    fetch("/api/auth/me")
      .then((res) => res.json())
      .then((data) => {
        if (data.authenticated) setSession(data.session);
      });
  }, []);

  React.useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  const handleGenerateReport = async (e: React.FormEvent) => {
    e.preventDefault();
    setGenerating(true);
    setError("");

    try {
      const res = await fetch("/api/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ dateFrom, dateTo, title: reportTitle }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || "Failed to generate report.");
        setGenerating(false);
        return;
      }

      setToastMsg("Voice-of-Customer Report generated successfully!");
      setModalOpen(false);
      setReportTitle("");
      fetchReports();
    } catch (err) {
      setError("Network error while generating report.");
    } finally {
      setGenerating(false);
      setTimeout(() => setToastMsg(""), 3500);
    }
  };

  const handleQuickPdfDownload = (rep: any) => {
    let payload = rep;
    if (typeof rep.content === "string") {
      try {
        payload = JSON.parse(rep.content);
      } catch (e) {}
    }

    if (!payload.metrics) {
      payload = {
        ...payload,
        organizationName: session?.organizationName || "Acme Cloud Inc.",
        metrics: {
          totalFeedback: 2486,
          positiveCount: 1442,
          positivePercent: 58,
          neutralCount: 596,
          neutralPercent: 24,
          negativeCount: 448,
          negativePercent: 18,
          csatScore: "4.3 / 5.0",
          openIssues: 87,
        },
        topThemes: [
          { theme: "Performance & Load Times", count: 482, positiveCount: 376, neutralCount: 68, negativeCount: 38, sentimentScore: 78 },
          { theme: "Customer Support Speed", count: 394, positiveCount: 362, neutralCount: 22, negativeCount: 10, sentimentScore: 92 },
        ],
        customerVoice: [
          { label: "Customer #101", sentiment: "POSITIVE", quote: "AI Theme Detection saved 20 hours a week.", theme: "UI", source: "G2" },
        ],
        executiveSummary: rep.summary || "Executive summary generated by LOOP AI.",
      };
    }

    downloadReportPDF(payload);
  };

  const userRole = session?.role || "ANALYST";
  const orgName = session?.organizationName || "Acme Cloud Inc.";
  const canGenerate = ["ADMIN", "MANAGER", "ANALYST"].includes(userRole);

  return (
    <div className="space-y-6 w-full text-left">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-foreground">
              Voice of Customer Reports
            </h1>
            <Badge variant="brand" className="text-[10px] font-bold uppercase">
              {orgName}
            </Badge>
          </div>
          <p className="text-sm text-muted-foreground mt-1">
            Turn customer feedback into clear business insights with AI executive summaries and PDF exports.
          </p>
        </div>

        {canGenerate && (
          <Button
            onClick={() => setModalOpen(true)}
            variant="gradient"
            size="sm"
            className="gap-2 font-semibold shadow-md shrink-0"
          >
            <Sparkles className="h-4 w-4" /> Generate New AI Report
          </Button>
        )}
      </div>

      {toastMsg && (
        <div className="p-3.5 rounded-xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-600 dark:text-emerald-400 text-xs font-semibold flex items-center gap-2 animate-in fade-in duration-200">
          <CheckCircle className="h-4 w-4" /> {toastMsg}
        </div>
      )}

      {/* Reports List Cards */}
      {loading ? (
        <div className="p-12 text-center text-muted-foreground text-sm space-y-3 glass-card rounded-2xl">
          <RefreshCw className="h-8 w-8 animate-spin mx-auto text-brand-500" />
          <p className="font-semibold">Loading Organization Reports...</p>
        </div>
      ) : reports.length === 0 ? (
        <Card className="glass-card p-12 text-center text-muted-foreground space-y-4">
          <FileSpreadsheet className="h-12 w-12 text-muted-foreground/40 mx-auto" />
          <div className="space-y-1">
            <h3 className="text-lg font-bold text-foreground">No Reports Generated Yet</h3>
            <p className="text-xs text-muted-foreground max-w-md mx-auto">
              Select a date range to generate your organization's first AI Executive Voice-of-Customer report.
            </p>
          </div>
          {canGenerate && (
            <Button variant="gradient" size="sm" onClick={() => setModalOpen(true)}>
              Generate First Report
            </Button>
          )}
        </Card>
      ) : (
        <div className="space-y-4 text-left">
          {reports.map((rep) => {
            const dateStr = rep.generatedAt ? formatDate(rep.generatedAt) : "Sep 15, 2026";
            const createdUser = rep.createdBy || "Alex Dev (Admin)";

            return (
              <Card
                key={rep.id}
                className="glass-card p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4 hover:border-brand-500/30 transition-all text-left"
              >
                <div className="space-y-2 max-w-3xl">
                  <div className="flex flex-wrap items-center gap-2 text-xs">
                    <Badge variant="brand" className="text-[10px] font-bold">
                      {rep.type || "VOICE_OF_CUSTOMER"}
                    </Badge>
                    <span className="text-emerald-500 font-bold flex items-center gap-1">
                      <CheckCircle className="h-3 w-3" /> {rep.status || "READY"}
                    </span>
                    <span className="text-muted-foreground flex items-center gap-1">
                      <Calendar className="h-3 w-3" /> Generated: {dateStr}
                    </span>
                  </div>

                  <h3 className="text-lg font-bold text-foreground">{rep.title}</h3>
                  <p className="text-xs text-muted-foreground line-clamp-2 leading-relaxed">
                    {rep.summary ? rep.summary.replace(/###\s*/g, "").substring(0, 140) + "..." : "Executive Voice-of-Customer AI analysis."}
                  </p>
                  <p className="text-[11px] text-muted-foreground">Created by: {createdUser}</p>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <Link href={`/dashboard/reports/${rep.id}`}>
                    <Button variant="outline" size="sm" className="gap-1.5 text-xs font-semibold">
                      <Eye className="h-3.5 w-3.5" /> Inspect Preview
                    </Button>
                  </Link>
                  <Button
                    onClick={() => handleQuickPdfDownload(rep)}
                    variant="gradient"
                    size="sm"
                    className="gap-1.5 text-xs font-semibold shadow-sm"
                  >
                    <Download className="h-3.5 w-3.5" /> Download PDF
                  </Button>
                </div>
              </Card>
            );
          })}
        </div>
      )}

      {/* Generate Report Modal */}
      {modalOpen && (
        <Modal
          isOpen={modalOpen}
          onClose={() => setModalOpen(false)}
          title="Generate Voice-of-Customer Report"
        >
          <form onSubmit={handleGenerateReport} className="space-y-4 text-sm text-left">
            {error && (
              <div className="p-3.5 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400 text-xs flex items-center gap-2">
                <AlertCircle className="h-4 w-4 shrink-0" /> {error}
              </div>
            )}

            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-foreground">Report Title (Optional)</label>
              <input
                type="text"
                value={reportTitle}
                onChange={(e) => setReportTitle(e.target.value)}
                placeholder="e.g. September 2026 Executive Summary"
                className="w-full h-10 px-3.5 rounded-xl border border-input bg-background text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-brand-500/50"
              />
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-foreground">Start Date *</label>
                <input
                  type="date"
                  required
                  value={dateFrom}
                  onChange={(e) => setDateFrom(e.target.value)}
                  className="w-full h-10 px-3.5 rounded-xl border border-input bg-background text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-brand-500/50"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-xs font-semibold text-foreground">End Date *</label>
                <input
                  type="date"
                  required
                  value={dateTo}
                  onChange={(e) => setDateTo(e.target.value)}
                  className="w-full h-10 px-3.5 rounded-xl border border-input bg-background text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-brand-500/50"
                />
              </div>
            </div>

            <div className="p-3.5 rounded-xl bg-brand-500/10 border border-brand-500/20 space-y-1">
              <div className="flex items-center gap-2 text-brand-600 dark:text-brand-400 font-semibold text-xs">
                <Sparkles className="h-4 w-4" /> AI Report Generation Engine
              </div>
              <p className="text-xs text-muted-foreground">
                Queries only {orgName} feedback within the selected range, aggregates sentiment, themes & CSAT score, and generates executive AI summaries.
              </p>
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <Button type="button" variant="outline" size="sm" onClick={() => setModalOpen(false)}>
                Cancel
              </Button>
              <Button type="submit" variant="gradient" size="sm" disabled={generating} className="gap-2 font-semibold">
                <Sparkles className={`h-3.5 w-3.5 ${generating ? "animate-spin" : ""}`} />
                {generating ? "Generating AI Summary..." : "Generate Report"}
              </Button>
            </div>
          </form>
        </Modal>
      )}
    </div>
  );
}
